---
name: release
on:
  push:
    tags:
      - '*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: |
          export TZ=UTC
          uv sync --group release --all-extras --no-dev
          uv run pyinstaller auth-playground.spec
          uv cache prune --ci
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            dist/auth-playground
